### ISSUE TITLE
Error trying to knit

### ISSUE THREAD

**Issue by anthonyalbrecht** [AaronGullickson/final_project_gender_gap#1]
Quitting from lines 58-80 (full_report.Rmd) 
Error in is.data.frame(data) : object 'cps' not found
Calls: <Anonymous> ... <Anonymous> -> model.frame.default -> is.data.frame
Execution halted

**Comment by AaronGullickson** [comment]
@anthonyalbrecht It is saying that you have not loaded the `cps` data. That should be loaded in the very first code chunk. Can you commit and push your changes so that I can see them on GitHub? Then it will be easy to diagnose.

**Comment by anthonyalbrecht** [comment]
That is bizarre. I just re-loaded the CPS data to commit and push. Let me know if worked. However, I do not believe so since it did not show up under my git tab.

**Comment by AaronGullickson** [comment]
@anthonyalbrecht You need to commit and push the changes to your `report.Rmd` file. You commit and pushed changes to two other unnecessary files.

**Comment by anthonyalbrecht** [comment]
@AaronGullickson I just made another attempt. I am leaving town soon so if that did not work, is there anyway I can set up a call with you tomorrow? I know it is due today and am trying my best to turn it in on time but I will soon not have service.

**Comment by AaronGullickson** [comment]
@anthonyalbrecht Nothing is changed. You need to push your changes as well as commit them. You can always go to your own github repository and see if the changes are showing there. Please try again as soon as you can.

**Comment by anthonyalbrecht** [comment]
@AaronGullickson I do not see the changes in my github repository. I have facetimed my group partners and they are lost as to what the problem may be as it appears I have followed the same steps like them. While it may be a hassle, could I copy and paste my project and send it to you and we meet after break to actually submit it? I am at a loss for solutions on my end. Sorry for the inconvenience to you.

**Comment by AaronGullickson** [comment]
@anthonyalbrecht I am just now seeing this. You are posting this in the group project repository. You should post issues about your project in your individual project repository. Send me your `report.Rmd` file ASAP and I will consider evaluating it and changing your grade.

**Comment by AaronGullickson** [comment]
@anthonyalbrecht Check that, actually. You posted that on my own copy of the project repository which suggests the possible problem. If you cloned off of this repository instead of your own as the instructions stated, then you will not have permission to push. When you have your project open in RStudio try opening a terminal window from the tools menu and then type into the terminal prompt:

```
git remote remove origin
git remote add origin https://github.com/UOSOC312/final-project-gender-gap-anthonyalbrecht.git
git push -u origin master
```

If that does not work, you can email me your `report.Rmd`.
